name: fl_prac_5
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.2.0
  get_it: ^8.0.0
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3
  build_runner: ^2.4.0

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true